dist: trusty
language: go
go:
  - 1.9
services:
  - postgresql
before_script:
  - createdb vulcanize_private
  - psql vulcanize_private < migrations/schema.sql
script:
  - go test -v ./pkg/...
notifications:
  email: false
