dist: trusty
language: go
go:
  - 1.9
services:
  - postgresql
before_script:
  - createdb vulcanize
  - psql vulcanize < migrations/schema.sql
script:
  - go test -v ./core/...
notifications:
  email: false
